spring.config.import=optional:file:.env[.properties]
spring.application.name=api-gateway

server.port=8083
jwt.secret=${JWT_SECRET}

services.auth-service=${SERVICES_AUTH_SERVICE}
services.order-service=${SERVICES_ORDER_SERVICE}
services.user-service=${SERVICES_USER_SERVICE}
services.payment-service=${SERVICES_PAYMENT_SERVICE}