spring.config.import=optional:file:.env[.properties]
spring.application.name=api-gateway

server.port=8083
jwt.secret=${JWT_SECRET}

services.auth-service=${SERVICES_AUTH_SERVICE:http://auth-service:8081}
services.order-service=${SERVICES_ORDER_SERVICE:http://order-service:8082}
services.user-service=${SERVICES_USER_SERVICE:http://user-service:8080}
services.payment-service=${SERVICES_PAYMENT_SERVICE:http://payment-service:8084}