spring.config.import=optional:file:.env[.properties]
spring.application.name=api-gateway

server.port=8083

services.order-service=${SERVICES_ORDER_SERVICE:http://order-service:8082}
services.user-service=${SERVICES_USER_SERVICE:http://user-service:8080}
services.payment-service=${SERVICES_PAYMENT_SERVICE:http://payment-service:8084}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://keycloak:8085/realms/internship/protocol/openid-connect/certs}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=${cors.allowed-origins}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
